matrix:
  include:
    - language: python
      os:
        - linux
        # Travis does not support python on osx yet.
        # see: https://github.com/travis-ci/travis-ci/issues/2312
        # - osx
      python:
        - "2.7"
        - "3.3"
      # Test the install script.
      script:
        - ./install.py
        - ./install_test.py

    - language: bash
      os:
        - linux
      addons:
        apt:
          packages:
            - ksh
            - zsh
      env:
        - PATH=$HOME/bin/:$PATH
        - SHFMT_VERSION=v2.6.2
        - SHFMT_DOWNLOAD_URL="https://github.com/mvdan/sh/releases/download/${SHFMT_VERSION}/shfmt_${SHFMT_VERSION}_linux_amd64"
      before_script:
        - $SHELL --version 2>/dev/null || dpkg -s "$SHELL" 2>/dev/null || command -v "$SHELL"
        - curl --version
        - shellcheck --version
        - curl -sSL "$SHFMT_DOWNLOAD_URL" -o $HOME/bin/shfmt;
        - chmod +x $HOME/bin/shfmt;
        - shfmt --version
      script:
        - ./install_test.sh

    - language: minimal
      os:
        - osx
      before_script:
        - brew tap caskroom/cask
        - brew install cask powershell
      script:
        - pwsh install_test.ps1
